<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Chassis Link -->
    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <origin xyz="${chassis_length/2} 0.0 ${chassis_height/2}"/>
            <material name="green"/>
        </visual>

        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <origin xyz="${chassis_length/2} 0.0 ${chassis_height/2}"/>
        </collision>

    </link> 

    <!-- Chassis joint -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0.0 0.0 0.0"/>
    </joint>

    <gazebo reference="chassis_link">
        <material> Gazebo/Grey </material>
    </gazebo>

</robot>
